metricsServer: "http://prometheus-operated:9090"

# creates serviceMonitor for monitoring Flagger metrics
serviceMonitor:
  enabled: true
  honorLabels: true
  # Set the namespace the ServiceMonitor should be deployed
  namespace: monitoring
  # Set labels for the ServiceMonitor, use this to define your scrape label for Prometheus Operator
  # labels:

# accepted values are kubernetes, istio, linkerd, appmesh, contour, nginx, gloo, skipper, traefik, apisix, osm
meshProvider: "nginx"