grafana:
  enabled: true
  adminPassword: prom-operator
  grafana.ini:
    server:
      domain: naavre-dev.minikube.test
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
      serve_from_sub_path: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
        - naavre-dev.minikube.test
    path: /grafana

  persistence:
    enabled: true


prometheus:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /$2
    hosts:
        - naavre-dev.minikube.test
    paths:
        - /prometheus(/|$)(.*)
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    externalUrl: "https://naavre-dev.minikube.test/prometheus"
#     routePrefix: /prometheus
    additionalScrapeConfigs:
        - job_name: 'ingress-nginx-endpoints'
          kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
              - ingress-nginx
          relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
            action: replace
            target_label: __scheme__
            regex: (https?)
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
          - source_labels: [__meta_kubernetes_service_name]
            regex: prometheus-server
            action: drop





