singleNamespace: true
controller:
  resources:
    requests:
      cpu: 900m
      memory: 512Mi
    limits:
      cpu: 1800m
      memory: 1024Mi
  containerRuntimeExecutor: emissary
  parallelism: 12
  resourceRateLimit:
    limit: 40
    burst: 10
server:
  resources:
    requests:
      ephemeral-storage: 512Mi
  extraArgs:
    - --auth-mode=sso
    - --auth-mode=client
  enabled: true
  baseHref: /argowf/
  serviceType: ClusterIP
  sso:
    enabled: true
    issuer: https://naavre-dev.minikube.test/auth/realms/vre
    insecureSkipVerify: true
    sessionExpiry: 240h
    clientId:
      name: argo-sso
      key: client-id-key
    clientSecret:
      name: argo-sso
      key: client-secret-key
    redirectUrl: https://naavre-dev.minikube.test/argowf/oauth2/callback
    rbac:
      enabled: false
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/add-base-url: "true"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header Accept-Encoding "";
        sub_filter '<base href="/">' '<base href="/argowf/">';
        sub_filter_once on;
        more_set_headers "X-Accel-Buffering: no";
    hosts:
      - naavre-dev.minikube.test
    paths:
      - /argowf(/|$)(.*)
    tls: []
