namespace: test

image:
  tag: 6.7.0

service:
    enabled: false
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: naavre-dev.minikube.test
      paths:
        - path: /podinfo(/|$)(.*)
          pathType: ImplementationSpecific