k8s_yaml(helm(
  './submodules/VREPaaS-helm-charts/',
  name='vrepaas',
  values=[
    './helm/values.yaml',
    ],
  ))

k8s_resource(
  'vrepaas-vreapi',
  labels=['VREPaaS'],
  links=['https://naavre-dev.minikube.test/vre-api-test/api/',
         'https://naavre-dev.minikube.test/vre-api-test/admin/'],
  resource_deps=['keycloak'],
  )
k8s_resource(
  'vrepaas-vreapp',
  labels=['VREPaaS'],
  links=[ 'https://naavre-dev.minikube.test/vreapp/'],
  resource_deps=['keycloak'],
  )
k8s_resource(
  'vrepaas-postgresql',
  labels=['VREPaaS'],
  )

custom_build(
    'qcdis/vreapi',
    'docker buildx build ./submodules/VREPaaS -f ./submodules/VREPaaS/tilt/vreapis/Dockerfile -t $EXPECTED_REF --push',
    ['./submodules/VREPaaS/vreapis'],
    skips_local_docker=True,
    disable_push=True,
    entrypoint='/app/entrypoint.dev.sh',
    live_update=[
        sync('./submodules/VREPaaS/vreapis', '/app'),
        run('cd /app && /opt/venv/bin/python manage.py makemigrations'),
        run('cd /app && /opt/venv/bin/python manage.py migrate'),
        run('cd /app && /opt/venv/bin/pip install -r requirements.txt',
             trigger='./submodules/VREPaaS/vreapis/requirements.txt'),
    ],
)
custom_build(
    'qcdis/vreapp',
    'docker buildx build ./submodules/VREPaaS -f ./submodules/VREPaaS/tilt/vre-panel/Dockerfile -t $EXPECTED_REF --push',
    ['./submodules/VREPaaS/vre-panel'],
    skips_local_docker=True,
    disable_push=True,
    live_update=[
        sync('./submodules/VREPaaS/vre-panel', '/app'),
        run('cd /app && npm install',
            trigger=['./submodules/VREPaaS/vre-panel/package.json'])
    ],
)
