hub:
  image:
    tag: "2.0.0"
  concurrentSpawnLimit: 20
  consecutiveFailureLimit: 20
  activeServerLimit: 20
  namedServerLimitPerUser: 1
  shutdownOnLogout: true
  extraEnv:
    OAUTH2_TLS_VERIFY: 'false'
  baseUrl: /n-a-a-vre
  config:
    Authenticator:
      admin_users:
      - admin
      allowed_users:
      - user
    DummyAuthenticator:
      password: user
    JupyterHub:
      authenticator_class: dummy
#    GenericOAuthenticator:
#      client_id: naavre
#      client_secret: fake_openid_client_secret
#      authorize_url: https://naavre-dev.minikube.test/auth/realms/vre/protocol/openid-connect/auth
#      token_url: https://naavre-dev.minikube.test/auth/realms/vre/protocol/openid-connect/token
#      userdata_url: https://naavre-dev.minikube.test/auth/realms/vre/protocol/openid-connect/userinfo
#      oauth_callback_url: https://naavre-dev.minikube.test/n-a-a-vre/hub/oauth_callback
#      login_service: keycloak
#      username_key: preferred_username
#      userdata_params:
#        state: state
#      claim_groups_key: groups
#      allowed_groups:
#        - users
#      admin_groups:
#        - admins
#    JupyterHub:
#      authenticator_class: generic-oauth
#      tls_verify: false
ingress:
  enabled: true
  hosts:
    - naavre-dev.minikube.test
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/add-base-url: "true"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "600m"
    nginx.org/client-max-body-size: "600m"
proxy:
  service:
    type: ClusterIP
prePuller:
  continuous:
    enabled: false
  hook:
    enabled: false
singleuser:
  extraAnnotations:
    backup.velero.io/backup-volumes: pvc-volume,emptydir-volume
  cmd: ['/usr/local/bin/start-jupyter-venv.sh']
  extraFiles:
    jupyter_notebook_config.json:
      mountPath: /etc/jupyter/jupyter_notebook_config.json
      data:
        ServerApp:
          iopub_data_rate_limit: 1.0e10
          iopub_msg_rate_limitFloat: 3000
  lifecycleHooks:
    postStart:
      exec:
        command: ["sh", "-c", "/tmp/init_script.sh"]
  defaultUrl: "/lab"
  extraEnv:
    API_ENDPOINT: http://naavre-dev.minikube.test/vre-api-test
    NAAVRE_API_TOKEN: token_vreapi
    CELL_GITHUB: https://github.com/QCDIS/NaaVRE-cells-test
    CELL_GITHUB_TOKEN: ""
    JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    MODULE_MAPPING_URL: https://raw.githubusercontent.com/QCDIS/NaaVRE-conf/main/module_mapping.json
    MULTIPLY_CONF_URL: https://github.com/QCDIS/data-access/raw/master/multiply.zip
    PROJ_LIB: /venv/share/proj
    REGISTRY_URL: https://hub.docker.com/u/qcdis
    SEARCH_API_ENDPOINT: ""
    SEARCH_API_TOKEN: ""
    VLAB_SLUG: n-a-a-vre
    ARGO_WF_SPEC_SERVICEACCOUNT: executor
    VOL2BIRD_BASE_IMAGE_TAG: v2.1
    MINICONDA3_PDAL_BASE_IMAGE_TAG: v0.14
    R_BASE_IMAGE_TAG: 70178b8e48d7

  image:
    name: qcdis/n-a-a-vre-dev
    tag: latest
    pullPolicy: Never
