hub:
  image:
    tag: "2.0.0"
  concurrentSpawnLimit: 20
  consecutiveFailureLimit: 20
  activeServerLimit: 20
  namedServerLimitPerUser: 1
  shutdownOnLogout: true
  extraConfig:
    templates: |
      c.JupyterHub.services += [ { 'name': 'service-prometheus',
                                    'api_token': 'EXAMPLE_TOKEN'}]
      c.JupyterHub.load_roles += [ { 'name': 'service-metrics-role',
                                        'description': 'access metrics',
                                        'scopes': [ 'read:metrics'],
                                        'services': ['service-prometheus']}]
  extraEnv:
    OAUTH2_TLS_VERIFY: 'false'
  baseUrl: /n-a-a-vre-integration
  config:
    GenericOAuthenticator:
      client_id: naavre
      client_secret: fake_openid_client_secret
      authorize_url: https://naavre-dev.minikube.test/auth/realms/vre/protocol/openid-connect/auth
      token_url: https://naavre-dev.minikube.test/auth/realms/vre/protocol/openid-connect/token
      userdata_url: https://naavre-dev.minikube.test/auth/realms/vre/protocol/openid-connect/userinfo
      oauth_callback_url: https://naavre-dev.minikube.test/n-a-a-vre-integration/hub/oauth_callback
      login_service: keycloak
      username_key: preferred_username
      userdata_params:
        state: state
    JupyterHub:
      authenticator_class: generic-oauth
      tls_verify: false
ingress:
  enabled: true
  hosts:
    - naavre-dev.minikube.test
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/add-base-url: "true"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "600m"
    nginx.org/client-max-body-size: "600m"
proxy:
  service:
    type: ClusterIP
prePuller:
  continuous:
    enabled: false
  hook:
    enabled: false
singleuser:
  cmd: ['/usr/local/bin/start-jupyter-venv.sh']
  extraFiles:
    jupyter_notebook_config.json:
      mountPath: /etc/jupyter/jupyter_notebook_config.json
      data:
        ServerApp:
          iopub_data_rate_limit: 1.0e10
          iopub_msg_rate_limitFloat: 3000
  lifecycleHooks:
    postStart:
      exec:
        command: ["sh", "-c", "/tmp/init_script.sh"]
  defaultUrl: "/lab"
  extraEnv:
    API_ENDPOINT: http://naavre-dev.minikube.test/vre-api-test
    NAAVRE_API_TOKEN: token_vreapi
    CELL_GITHUB: ""
    CELL_GITHUB_TOKEN: ""
    JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    MODULE_MAPPING_URL: https://raw.githubusercontent.com/QCDIS/NaaVRE-conf/main/module_mapping.json
    PROJ_LIB: /venv/share/proj
    SEARCH_API_ENDPOINT: ""
    SEARCH_API_TOKEN: ""
    VLAB_SLUG: n-a-a-vre
    ARGO_WF_SPEC_SERVICEACCOUNT: executor
    VRE_API_VERIFY_SSL: 'false'
  image:
    name: qcdis/n-a-a-vre-dev
    tag: latest
    pullPolicy: Never
