load('ext://helm_remote', 'helm_remote')

helm_remote(
  'traefik',
  repo_name='traefik',
  repo_url='https://traefik.github.io/charts',
  version='28.2.0',
  values=[
    './helm/values.yaml',
    ]
  )

k8s_resource(
  'traefik',
  labels=['traefik'],
  links=['https://minikube.test/traefik/']
  )
