auth:
  rootPassword: "password"

ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: "naavre-dev.minikube.test"
  path: /minio/(.*)
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1

extraEnvVars:
    - name: MINIO_CONSOLE_SUBPATH
      value: "/minio/"
    - name: MINIO_BROWSER_REDIRECT_URL
      value: "https://naavre-dev.minikube.test/minio/"
    - name : INIO_IDENTITY_OPENID_CONFIG_URL
      valude: "https://openid-provider.example.net/.well-known/openid-configuration"
    - name : MINIO_IDENTITY_OPENID_CLIENT_ID
      valude: "my-client-id"
    - name : MINIO_IDENTITY_OPENID_CLIENT_SECRET
      valude: "my-client-secret"
    - name : MINIO_IDENTITY_OPENID_CLAIM_NAME
      valude: "email"
    - name : MINIO_IDENTITY_OPENID_CLAIM_PREFIX
      valude: "oidc:"
    - name : MINIO_IDENTITY_OPENID_SCOPES
      valude: "openid,email"
    - name : MINIO_IDENTITY_OPENID_REDIRECT_URI
      valude: "https://naavre-dev.minikube.test/minio/dex/callback"
    - name : MINIO_IDENTITY_OPENID_COMMENT
      valude: "My OpenID Connect Provider"




apiIngress:
  enabled: true
  ingressClassName: "nginx"
  hostname: "naavre-dev.minikube.test"
  path: "/minio-api"
