# load('ext://helm_remote', 'helm_remote')
# helm_remote(
#   'minio',
#   repo_name='bitnami',
#   repo_url='https://charts.bitnami.com/bitnami',
#   version='12.10.3',
#   values=[
#     './helm/values.yaml',
#    ]
# )
#
# k8s_resource('minio', labels=['minio'],
#              links=['https://naavre-dev.minikube.test/minio/'])


docker_compose("./docker-compose/docker-compose.yml")
