global:
  environment: test

  ingress:
    host: "naavre-dev.minikube.test"

  base_paths:
    development:
      vreapi: "/vre-api-test"
      vreapp: "/vreapp"

  keycloak:
    url: https://naavre-dev.minikube.test/auth
    realm: vre
    client_id: naavre
    client_secret_key: fake_openid_client_secret

  argo:
    namespace: default
    url: https://naavre-dev.minikube.test/argowf
    token: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6InFoMXRDRnRZakVtUXlMZl9PMVNrelAtMUtOM19fSVZ5TU5Qc0VMVnZWeUEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InZyZS1hcGkuc2VydmljZS1hY2NvdW50LXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InZyZS1hcGkiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI1NDY0ZmJiNS01MTdjLTRmNmMtOWI3MC0zODZiMjhhNjkzZjgiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVmYXVsdDp2cmUtYXBpIn0.0r4j1HcHfBIonrA8F_GluG6Ox8CdZkM81201czzbouq1WXJ63LUHLGQIDoZoeivHMd5L-0OPb8sV9L2CumnZUlxbsrmTU2SrDh9bcWLuPpU-GcBUnkblotGNDJ1evT9vZSk8f1pEKD-td9MdK4lH1j5eNWvXx0DBQGue-iosoCUj22pD4XB1tSF8doKBHxSTNI75ADfZY9mqIImc8ExWp3deDdDSJ68aAPPsTd2HmjYjwzOLGcC-MSPUteBU9cOTMBdApqsjB6MbN0KQVKkXdSTwfvUN0VJ4XZSHhvUQVHm7uj5yrw-JudqBozfLKXr0iSStjMEpgJGbItFUuwD4Cg

  k8s_secret_creator:
    url: https://naavre-dev.minikube.test/k8s-secret-creator/1.0.0/
    token: token_ksc

vreapi:
  secret_key: "dev_secret_key_vreapi"
  auth:
    superuser_email: "admin@naavre-dev.minikube.test"
    superuser_username: "admin"
    superuser_password: "admin"
    username: "user"
    password: "user"
    token: "token_vreapi"
  insecureSkipTLSVerification: true

vreapp:
  secret_key: "dev_secret_key_vreapp"
  insecureSkipTLSVerification: true
