global:
  environment: test

  ingress:
    host: "naavre-dev.minikube.test"

  base_paths:
    development:
      vreapi: "/vre-api-test"
      vreapp: "/vreapp"

  keycloak:
    url: https://naavre-dev.minikube.test/auth
    realm: vre
    client_id: naavre
    client_secret_key: fake_openid_client_secret

  argo:
    namespace: default
    url: https://naavre-dev.minikube.test/argowf
    token: Bearer {output of kubectl get secret vre-api.service-account-token -o jsonpath='{.data.token}' | base64 -d}

vreapi:
  secret_key: "dev_secret_key_vreapi"
  auth:
    superuser_email: "admin@naavre-dev.minikube.test"
    superuser_username: "admin"
    superuser_password: "admin"
    username: "user"
    password: "user"
    token: "token_vreapi"
  insecureSkipTLSVerification: true

vreapp:
  secret_key: "dev_secret_key_vreapp"
  insecureSkipTLSVerification: true
